[package]
name = "reagent"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
edition = "2018"

[dependencies]
ramhorns = "0.5.0"
serde = { version = "1.0.89", features = ["derive"] }
toml = "0.4.2"
