# Section generated by <reagent>
prefix ?= /usr/local
exec_prefix = $(prefix)
bindir = $(exec_prefix)/bin
libdir = $(exec_prefix)/lib
includedir = $(prefix)/include
datarootdir = $(prefix)/share
datadir = $(datarootdir)

.PHONY: all clean distclean format install uninstall run test update FORCE

BIN=reagent

all: target/release/$(BIN)

clean:
	cargo clean

distclean: clean
	rm -rf .cargo vendor

format:
	cargo fmt --all

install: all
	install -D -m 0755 "target/release/$(BIN)" "$(DESTDIR)$(bindir)/$(BIN)"

uninstall:
	rm -f "$(DESTDIR)$(bindir)/$(BIN)"

run: target/release/$(BIN)
	"$<"

test:
	cargo test

update:
	cargo update

FORCE:

.cargo/config:
	mkdir -p .cargo
	echo '[source.crates-io]' > "$@"
	echo 'replace-with = "vendor"' >> "$@"
	echo >> "$@"
	echo '[source.vendor]' >> "$@"
	echo 'directory = "vendor"' >> "$@"

vendor: .cargo/config
	cargo vendor
	touch vendor

target/release/$(BIN): FORCE
	if [ -d vendor ]; \
	then \
		cargo build --release --frozen; \
	else \
		cargo build --release; \
	fi
# </reagent>
